### ISSUE TITLE
does govbook have an "Account"? a hash tag?

### ISSUE THREAD

**Issue by eads** [thechicagoreporter/govbook#53]
What should the hashtag for govbook be? Should there be separate social media accounts for it? What's the hashtag?

**Comment by oobineme** [comment]
Hi @artfulaction , 
The answer to this ticket: there's no separate social accounts needed for GovBook. But is referenced in social shares, internal/external contributors for this TCR product can/should use '#govbook' when posting.

Please document that in the docs and then close this ticket. Thank you!

**Comment by artfulaction** [comment]
This is now documented in the GovBook Google Drive folder.
