### ISSUE TITLE
About subhead hides in the FAQ

### ISSUE THREAD

**Issue by oobineme** [thechicagoreporter/govbook#85]
Minor style issue: we could bold "GovBook provides basic contact information for every unit of government that reports to the Illinois Comptroller." It's an important line , so this is just so there is a better break between the Title and where the FAQs begin. 

I added a screenshot of the top of the MemVote doc for reference.

<img width="676" alt="govbook_about" src="https://user-images.githubusercontent.com/44822511/68043130-97037b00-fca2-11e9-81d4-eee0ce6c0ae8.PNG">
<img width="608" alt="memvote_screencapture" src="https://user-images.githubusercontent.com/44822511/68043132-97037b00-fca2-11e9-9b41-4429cf61841f.PNG">

**Comment by eads** [comment]
Just a note for @artfulaction -- @oobineme is the person to sync up with on the nitty gritty of the desire design changes here

**Comment by oobineme** [comment]
To test in isolation and continue playing with it add your modifications to a branch.
